# Generated by Django 2.0.6 on 2018-07-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='getter',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
