# Generated by Django 2.0.7 on 2018-07-05 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=60)),
                ('text_message', models.TextField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message_getter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('order_name', models.CharField(max_length=100)),
                ('getter_email', models.EmailField(max_length=254)),
                ('getter_name', models.CharField(max_length=60)),
                ('getter_surname', models.CharField(max_length=60)),
                ('status', models.SmallIntegerField(choices=[(0, 'Creating'), (100, 'Sended'), (80, 'Sending'), (25, 'Searching for transport'), (60, 'Waiting for transporting')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_leaving', models.DateTimeField()),
                ('time_arrival', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('max_weight', models.IntegerField()),
                ('total_weight', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Waiting for moving'), (100, 'Moving')], default=0)),
                ('punkt_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_punkt_to', to='main.Punkt')),
                ('punkt_where_staying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_punkt_where_staying', to='main.Punkt')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='punkt_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transporting_punkt_from', to='main.Punkt'),
        ),
        migrations.AddField(
            model_name='order',
            name='punkt_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transporting_punkt_to', to='main.Punkt'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transporting_vehicle', to='main.Vehicle'),
        ),
    ]
