# Generated by Django 2.0.6 on 2018-06-25 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('order_name', models.CharField(max_length=100)),
                ('getter_email', models.EmailField(max_length=254)),
                ('getter_name', models.CharField(max_length=60)),
                ('getter_surname', models.CharField(max_length=60)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_leaving', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('max_weight', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='punkt_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transporting_punkt_from', to='main.Punkt'),
        ),
        migrations.AddField(
            model_name='order',
            name='punkt_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transporting_punkt_to', to='main.Punkt'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transporting_vehicle', to='main.Vehicle'),
        ),
    ]
