# Generated by Django 2.0.7 on 2018-07-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='total_weight',
            field=models.IntegerField(default=0),
        ),
    ]
