# Generated by Django 2.0.7 on 2018-07-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='max_way',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='punkt_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_punkt_to', to='main.Punkt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='punkt_where_staying',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_punkt_where_staying', to='main.Punkt'),
            preserve_default=False,
        ),
    ]
