# Generated by Django 2.0.6 on 2018-06-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sending_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
